juanPedroGalarza/mytinerary-juandream

src/components/Footer.js, src/styles/Footer.css
=> Basic Footer

src/App.js, src/components/Header.js, src/layouts/WebsiteLayout.js, src/pages/CitiesPage.js, src/pages/Hero.js
=> Issue 16 layout

src/App.js, src/components/Footer.js, src/components/Header.js, src/layouts/WebsiteLayout.js, src/pages/CitiesPage.js, src/pages/Hero.js, src/styles/Footer.css, src/styles/Header.css, src/styles/Hero.css
Update 1.1
-Header
-Layouts
-Styles
=> Sprint 1 test

src/layouts/ConstructionLayout.js
UnderConstruction layout created
=> UnderConstruction

src/components/Footer.js, src/components/Header.js, src/pages/CitiesPage.js, src/pages/Hero.js, src/styles/Footer.css, src/styles/Header.css, src/styles/Hero.css
🐙 Eventualmente quedara lindo.
=> CTA y estilos

src/components/TableList.jsx, src/pages/CitiesPage.js, src/pages/NewCity.js, src/styles/CitiesPage.css, src/styles/NewCity.css, src/styles/TableList.css
NewCity page created;
CitiesPage Created;
component TableList
styles no-responsive
=> NewCity - CitiesPage

src/components/CitiesCarousel.js, src/components/Header.js, src/components/TableList.jsx, src/layouts/ConstructionLayout.js, src/pages/CitiesPage.js, src/styles/CitiesPage.css, src/styles/Footer.css, src/styles/Hero.css, src/styles/TableList.css, src/styles/UnderConstruction.css
Los cambios de JS es para agregar la propiedad country, que es usada mayoritariamente en las tarjetas de cities.
Cambié el diseño basico del botón del Hero.
Mejora de responsive en general. (o tal vez no, a testear) 
Faltaria embellecer el carousel aun mas de lo que esta. 🐙
=> Cities styles

src/App.js, src/components/Carousel.js, src/components/Details.jsx, src/components/TableList.jsx, src/pages/City.js, src/styles/Carousel.css, src/styles/TableList.css
- Se creo City.js como página y Details.jsx como componente.
- Edite el un poco el App.js para cambiar una route e importar el City.js
- Los divs del carousel/ las cards de cities, dirigen a la pag de City.js, donde se genera una "Card" con el nombre, la imagen y el pais. Próximamente una descripcion. (?
🐙
=> Links and Details page

src/components/Footer.js, src/components/Header.js
agregue las keys al header y footer para evitar el error en consola
=> bug fix on render

src/styles/Footer.css
=> Footer Responsive

src/components/Carousel.js, src/components/Details.jsx, src/components/TableList.jsx, src/styles/Arrow.css, src/styles/Carousel.css, src/styles/CityDetails.css, src/styles/TableList.css
Responsive carousel y css para cityDetails
=> fixing responsive

src/components/Header.js, src/styles/Header.css
le agregue un efecto de transition al nav lateral en mobile🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙🐙
=> navbar transition

src/pages/NewCity.js, src/styles/NewCity.css
Cambie un poco los inputs del NewCity. 🐙
=> Improved newcity style

src/components/NewCity/Input.jsx
Se dinamizo los inputs con los datos requeridos. 
Toma datos y se renderiza mas dinamicamente.
=> Funcionalidad y dinamismo Input

src/components/TableList.jsx, src/pages/CitiesPage.js
Se modifico el component TableList.jsx y CitiesPage.js para que tomaran datos de la Api usando axios.
=> axios cities

src/pages/City.js
=> olvide agregar city.js

src/pages/EditCity.js
Edité la función putCity para hacer un pedido al servidor de editar una ciudad
=> put EditCity

src/components/SearchText.jsx
Componente para filtrar en cities page. (search Bar)
Toma datos, faltaria ver como conectar con el back.
=> basic search component

src/pages/NewCity.js, src/styles/CitiesPage.css, src/styles/EditCity.css, src/styles/NewCity.css
Funcionalidad de NewCity y styles.
=> NewCity y styles

src/App.js, src/components/Details.jsx, src/pages/City.js, src/pages/EditCity.js
=> edit one city

src/components/Itinerary/Activities.jsx, src/components/Itinerary/Comments.jsx, src/components/Itinerary/Itinerary.js, src/features/actions/activitiesAPI.js, src/features/actions/comentsAPI.js, src/features/actions/itinerariesAPI.js, src/features/store.js
=> base redux actions

src/App.js, src/pages/MyTineraries.js, src/styles/MyTineraries.css
- Cree el componente de la pagina MyTineraries
- Inserte el componente Itinerary
- Agregué la ruta de la respectiva pagina al App.js
=> My tineraries page

src/components/Details.jsx, src/components/Itinerary/Comments.jsx, src/components/Itinerary/Itinerary.js, src/features/actions/activitiesAPI.js, src/features/actions/commentsAPI.js, src/features/actions/itinerariesAPI.js, src/styles/MyTineraries.css, src/styles/itinerary/Activities.css, src/styles/itinerary/Comments.css, src/styles/itinerary/Itinerary.css
- Aplique los arreglos a los modify y delete.
-  Details funciona con redux.
-  Algunos detalles simples de css.
Subo ahora porque voy a cenar, por si volves antes que yo.
=> Somefixing

src/components/Details.jsx, src/pages/EditCity.js, src/pages/NewCity.js
Arregle los errores de ortografía en "fundation" de las cities
=> Foundation

src/features/actions/itinerariesAPI.js, src/pages/MyTineraries.js, src/styles/MyTineraries.css
- Arregle el problema de que aparecian todos los itinerarios
- Puse responsive (faltan mas estiloss)
- Agregue la función de eliminar itinerario y su respectivo botón
=> My tineraries

package-lock.json, package.json, public/index.html, src/App.js, src/components/Users/GoogleSignUp.jsx, src/features/actions/usersAPI.js, src/features/store.js, src/pages/NewCity.js, src/pages/SignUp.js, src/styles/SignUpPage.css
Falta agregar funcionalidad al Sign Up by google. y el Sign In.
=> Component g

src/components/Users/GoogleSignUp.jsx, src/pages/SignUp.js
Hay un espacio en el sign up xD
=> button active

src/components/Users/GoogleSignIn.jsx, src/features/actions/usersAPI.js, src/pages/SignIn.js, src/styles/SignInPage.css
- Modifiqué el reducer de signIn
- Cree el componente GoogleSignIn
- Arregle algo en los estilos
=> Google Login

src/pages/SignIn.js, src/pages/SignUp.js
El input signIn ya no arrastra valores vacios.
=> fixed input for real

src/components/Itinerary/Itinerary.js, src/features/actions/itinerariesAPI.js, src/pages/MyTineraries.js
=> Edit itinerary

src/App.js, src/components/Details.jsx, src/components/Itinerary/Comment.jsx, src/components/Itinerary/Comments.jsx, src/features/actions/commentsAPI.js, src/pages/NewItinerary.js, src/styles/itinerary/Comments.css
=> New itinerary & delete comment

src/components/Itinerary/Comments.jsx, src/components/Itinerary/Itinerary.js, src/pages/MyTineraries.js, src/styles/MyTineraries.css, src/styles/NewItinerary.css, src/styles/itinerary/Comments.css, src/styles/profile/ProfileNavList.css
Sorry me retrase una banda ayudando en una cosita. 
Faltaria crear itineraries/ comentarios.  Si me despierto rapido lo hago.
=> styles and clases

src/App.js, src/components/Alert.jsx, src/components/Header.js, src/components/Itinerary/Comment.jsx, src/components/Itinerary/Comments.jsx, src/components/Profile/ProfileNavList.jsx, src/components/Users/GoogleSignIn.jsx, src/components/Users/GoogleSignUp.jsx, src/features/actions/itinerariesAPI.js, src/features/store.js, src/features/user/userSlice.js, src/layouts/WebsiteLayout.js, src/pages/MyTineraries.js, src/pages/SignIn.js, src/pages/SignUp.js
- Arreglé warnings de la consola al menos los que pude
- Problemas de renderizado con redux toolkit query
- userSlice agruegado al store
- Funcionalidad de rutas  y navBar según rol de usuario
=> Fix and redux

src/App.js, src/components/Alert.jsx, src/components/Profile/ProfileNavList.jsx, src/features/actions/usersAPI.js, src/features/user/userSlice.js, src/pages/SignIn.js
- Funcionalidad de token en signIn
- Agregado verifyToken al cargar la pagina para conseguir los datos del usuario logeado
- Optimizados los componentes profileNavList y Alert
=> Local token

src/components/Details.jsx, src/components/Itinerary/DisplayComments.jsx, src/styles/CitiesPage.css, src/styles/CityDetails.css, src/styles/NewAdmin.css
=> typo & styles fix
